name: "Build & Release"

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:  # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    runs-on: ubuntu-latest # change to ubuntu-latest to support container actions
    
    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Get Version from pubspec.yaml
      - name: Get Version
        id: get_version
        run: echo "VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)" >> $GITHUB_ENV

      #6 Build APK
      - name: Build APK
        run: flutter build apk --release

      #7 Rename APK with Version
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/fresh4you_${{ env.VERSION }}.apk

      #8 Upload APK
      - name: Upload APK 
        uses: actions/upload-artifact@v4
        with:
          name: fresh4you_${{ env.VERSION }}
          path: build/app/outputs/flutter-apk/fresh4you_${{ env.VERSION }}.apk

